name: 'intercom_integration_tests'
version: '0.6.0'
profile: 'integration_tests'
config-version: 2
models:
  intercom:
    materialized: table
    intermediate:
      materialized: ephemeral
vars:
  intercom_schema: intercom_integration_tests
  intercom_source:
    intercom_admin_identifier: "admin_data"
    intercom_company_history_identifier: "company_history_data"
    intercom_company_tag_history_identifier: "company_tag_history_data"
    intercom_contact_company_history_identifier: "contact_company_history_data"
    intercom_contact_history_identifier: "contact_history_data"
    intercom_contact_tag_history_identifier: "contact_tag_history_data"
    intercom_conversation_contact_history_identifier: "conversation_contact_history_data"
    intercom_conversation_history_identifier: "conversation_history_data"
    intercom_conversation_part_history_identifier: "conversation_part_history_data"
    intercom_conversation_tag_history_identifier: "conversation_tag_history_data"
    intercom_tag_identifier: "tag_data"
    intercom_team_admin_identifier: "team_admin_data"
    intercom_team_identifier: "team_data"
seeds:
  intercom_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    admin_data:
      +column_types:
        id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"
    company_history_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
    company_tag_history_data:
      +column_types:
        company_updated_at: timestamp
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    contact_company_history_data:
      +column_types:
        contact_updated_at: timestamp
    contact_history_data:
      +column_types:
        created_at: timestamp
        signed_up_at: timestamp
        last_replied_at: timestamp
        last_contacted_at: timestamp
        last_email_clicked_at: timestamp
        last_email_opened_at: timestamp
    contact_tag_history_data:
      +column_types:
        contact_updated_at: timestamp
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    conversation_contact_history_data:
      +column_types:
        conversation_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        conversation_updated_at: timestamp
    conversation_history_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        first_contact_reply_created_at: timestamp
        updated_at: timestamp
        waiting_since: timestamp
        snoozed_until: timestamp
    conversation_part_history_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        author_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"
        created_at: timestamp
        conversation_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        conversation_updated_at: timestamp
        updated_at: timestamp
        assigned_to_type: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"
    conversation_tag_history_data:
      +column_types:
        conversation_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        conversation_updated_at: timestamp
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    tag_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    team_admin_data:
      +column_types:
        admin_id: "{{ 'varchar(100)'  if target.type in ('redshift', 'postgres') else 'string'}}"
        team_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    team_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
clean-targets:
- target
- dbt_modules
